USE Booking
GO

--SOLUTION
--SET TRANSACTION ISOLATION LEVEL REPEATBLE READ 
BEGIN TRANSACTION
SELECT * FROM OwnerBooking 
WHERE id = 6;

WAITFOR DELAY '00:00:10'

SELECT * FROM OwnerBooking 
WHERE id = 6;
COMMIT TRANSACTION;
