USE Booking
GO

--SOLUTION
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION
	SELECT * FROM OwnerBooking 
	WHERE id BETWEEN 1 AND 3;

	WAITFOR DELAY '00:00:10';

	SELECT * FROM OwnerBooking 
	WHERE id BETWEEN 1 AND 3;
COMMIT TRANSACTION
