USE Practice
GO

--SOLUTION
--SET TRANSACTION ISOLATION LEVEL REPEATBLE READ 
BEGIN TRANSACTION
SELECT * FROM Categories 
WHERE id = 2;

WAITFOR DELAY '00:00:10'

SELECT * FROM Categories 
WHERE id = 2;
COMMIT TRANSACTION;
